---
- hosts: rukia
  user: root
  sudo: yes

  vars_files:
  - ./secrets/vars/production.yml

  vars:
    hostname: rukia
    cloud: true
    pwd: /root

  roles:
  - wordpress

  tasks:
  - name: reboot the server
    command: reboot
    when: isFirstRun is defined
