---
- hosts: hinata
  user: root
  sudo: yes

  vars_files:
  - ./secrets/production.yml

  vars:
    hostname: hinata
    cloud: true
    pwd: /root

  roles:
  - common

  tasks:
  - name: reboot the server
    command: reboot
    when: isFirstRun is defined