---
- hosts: rukia
  user: root
  sudo: yes

  vars_files:
  - ./secrets/test.yml

  vars:
    hostname: rukia
    cloud: true
    pwd: /root

  roles:
  - mysql

  tasks:
#  - name: reboot the server
#    command: reboot