---
- hosts: mikasa
  vars:
    hostname: mikasa
    cloud: true
    pwd: /root
    nlf: true
  user: root
  sudo: yes
  tasks:
  - include: ./tasks/base.yml
  - include: ./tasks/apache.yml
  - include: ./tasks/node.yml
  - include: ./tasks/jenkins.yml

  - include: ./projects/liuxuelun.yml
#  - include: ./projects/nlf.yml
#    when: nlf




