---
- hosts: docker
  user: vagrant
  sudo: yes

  vars_files:
  - ./secrets/vars/production.yml

  vars:
    hostname: precise64
    cloud: false
    pwd: /home/vagrant
    isFirstRun: true

  roles:
  - docker

  handlers:
  - name: post shutdown pause
    pause: seconds=30