---
- hosts: vagrant
  vars:
    hostname: precise64
    cloud: false
    pwd: /home/vagrant

  user: vagrant
  sudo: yes

  tasks:
  - include: ./tasks/base.yml
  - include: ./tasks/apache.yml
  - include: ./tasks/node.yml

  - include: ./tasks/mysql.yml
  - include: ./tasks/wordpress.yml

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
