---
- hosts: hinata
  user: vagrant
  sudo: yes

  vars_files:
  - ./secrets/vars/production.yml

  vars:
    hostname: hinata
    cloud: false
    pwd: /root

  roles:
  - common

  tasks:
  - name: reboot
    command: reboot
    when: isFirstRun is defined