# Install Node
- name: install node pt 1
  shell: wget https://npmjs.org/install.sh

- name: install node pt 2
  shell: bash {{ pwd }}/install.sh

- name: install node pt 3
  shell: npm install -g n

- name: install node pt 4
  shell: n stable

- name: install node pkgs
  shell: npm install -g {{ item }}
  with_items:
  - express
  - forever

- name: node cleanup
  shell: rm {{ pwd }}/install.sh