- name: phpmyadmin
  apt: pkg={{ item }}
  with_items:
  - php5-mysql
  - phpmyadmin

- name: include phpmyadmin conf
  shell: echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/apache2.conf

- name: default allow no password
  copy: src=etc/phpmyadmin/config.inc.php dest=/etc/phpmyadmin/config.inc.php

- name: change upload filesize
  template: src=php.ini dest=/etc/php5/apache2/php.ini

- name: restart apache
  service: name=apache2 state=restarted