- name: wordpress
  shell: wget http://wordpress.org/latest.tar.gz
  when: isFirstRun is defined

- name: unzip tar
  shell: tar -xvzf {{ pwd }}/latest.tar.gz
  when: isFirstRun is defined

- name: clean up tar
  shell: rm latest.tar.gz
  when: isFirstRun is defined

- name: mv wp
  shell: mv {{ pwd }}/wordpress /var/www/wordpress
  ignore_errors: yes
  when: isFirstRun is defined

- name: setup mysql wp
  copy: src=var/www/wordpress/wordpress-mysql dest=/var/www/wordpress/wordpress-mysql
  when: isFirstRun is defined

- name: mysql script
  shell: mysql -u root --password={{ mysql_password }} < /var/www/wordpress/wordpress-mysql
  ignore_errors: yes
  when: isFirstRun is defined

- name: load wp-config.php
  copy: src=var/www/wordpress/wp-config.php dest=/var/www/wordpress/wp-config.php
  when: isFirstRun is defined

- name: add ssh to install plugins
  apt: pkg=libssh2-php state=present
  when: isFirstRun is defined

- name: give write access to www-data
  shell: chown www-data /var/www/wordpress/wp-content
  when: isFirstRun is defined

- name: increase upload limit
  copy: src=etc/apache2/php.ini dest=/etc/apache2/php.ini
  when: isFirstRun is defined

- name: install wp-cli
  command: wget https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

- name: make wp-cli executable
  command: chmod 755 {{ pwd }}/wp-cli.phar

- name: copy setup script
  template: src=wp-cli-setup.sh.j2 dest=/root/wp-cli-setup.sh

- name: setup wp
  shell: /bin/bash {{ pwd }}/wp-cli-setup.sh

#- name: restart apache
#  service: name=apache2 state=restarted
#  when: isFirstRun is defined