- name: update base
  apt: update_cache=yes upgrade=dist

- name: install base pkgs
  apt: pkg={{ item }} state=present
  with_items:
  - htop
  - curl
  - screen
  - tree
  - git
  - daemon
  - vim
  - unzip
  - rtorrent
  - python-mysqldb
  - openjdk-7-jre-headless
  - openjdk-7-jdk
  - traceroute

- name: setup authorized_keys
  copy: src=authorized_keys dest={{ pwd }}/.ssh/authorized_keys
  when: cloud

- name: mk vagrant .ssh
  file: dest={{ pwd }}/.ssh state=directory
  when: not cloud

- name: vagrant keys
  copy: src=authorized_keys-vagrant dest={{ pwd }}/.ssh/authorized_keys
  when: not cloud

- hostname: name={{ hostname }}
  when: cloud

- name: fix hostname
  template: src=hosts.j2 dest=/etc/hosts
  when: cloud

- name: reboot
  command: reboot
  when: isFirstRun is defined