- name: update base
  apt: update_cache=yes upgrade=dist

- name: install base pkgs
  apt: pkg={{ item }} state=present
  with_items:
  - linux-image-generic-lts-raring  #Install backported kernel
  - linux-headers-generic-lts-raring

- name: reboot into backported kernel
  shell: /sbin/reboot
  delay: 20

- name: add docker repository key to local keychain
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: install lxc
  shell: curl -s https://get.docker.io/ubuntu/ | sudo sh