- name: lxl1
  file: path=/root/reveal.js state=absent

- name: lxl2
  file: path=/var/www/liuxuelun state=directory

- name: lxl3
  shell: git clone https://github.com/hakimel/reveal.js.git

- name: lxl4
  shell: rm -rf /var/www/liuxuelun

- name: lxl5
  shell: mv reveal.js/ /var/www/liuxuelun

- name: lxl6
  copy: src=var/www/main.html dest=/var/www/liuxuelun/index.html

- name: lxl7
  copy: src=var/www/0{{ item }}.html dest=/var/www/liuxuelun/0{{ item }}.html
  with_items:
  - 1
  - 2
  - 3
  - 4

- name: lxl8
  copy: src=var/www/default.css dest=/var/www/liuxuelun/css/theme/default.css
